# Generated by Django 4.0.5 on 2022-09-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='site',
            name='state',
        ),
    ]
